import {seasons,splitSeasons,categories,readState,route,loadData,selectRows,sortRows,value,format,defaultSort,playerSeason,metricDescription,seasonData} from './data.js';
import {columns,traditionalStrip,roleSections} from './columns.js';
const app=document.querySelector('#app');let store;let state=readState(location.hash);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(changes)=>esc(route({...state,...changes}));
const label=c=>({traditional:'Standard',advanced:'Advanced',players:'Players',teams:'Teams',goalies:'Goalies',faceoffs:'Faceoffs'}[c]||c.toLowerCase().replace(/(^|\s)\S/g,t=>t.toUpperCase()));
const categoryTitle=()=>({players:'Player',teams:'Team',goalies:'Goalie',faceoffs:'Faceoff'}[state.category]);
const segmentNames={regular:'Regular season',post:'Playoffs',combined:'Regular season + playoffs',champ_series:'Championship Series'};
const current=()=>seasonData(store.years[state.season],state.segment);
function segmentControl(){return splitSeasons.includes(state.season)?`<div class="competition-filter"><label for="segment">Competition</label><select id="segment">${Object.entries(segmentNames).map(([key,name])=>`<option value="${key}" ${state.segment===key?'selected':''}>${name}</option>`).join('')}</select></div>`:'';}
function description(col){if(state.view==='traditional'&&col.key==='save_pct')return 'Official saves divided by saves plus goals allowed.';if(state.view==='traditional')return col.description||`Official box-score ${col.label}; rates use pooled official counts.`;const m=store.metadata[col.key];return col.description||(m?metricDescription(m):'Official box-score '+col.label);}
function header(){return `<header><nav class="primary" aria-label="Statistics categories">${categories.map(c=>`<a href="${link({category:c,player:'',sort:'',direction:'desc',position:'',search:''})}" class="${c===state.category?'active':''}" ${c===state.category?'aria-current="page"':''}>${label(c)}</a>`).join('')}</nav><div class="season-group"><span class="partial" title="Incomplete source schedule">${store.years[state.season].partial&&state.category==='teams'&&!state.player?'PARTIAL SEASON':''}</span><label class="sr-only" for="season">Season</label><select id="season">${seasons.map(y=>`<option ${y===state.season?'selected':''}>${y}</option>`).join('')}</select></div></header>`;}
function tabs(detail=false){return `<div class="view-controls"><nav class="secondary" aria-label="Statistic type">${['traditional','advanced'].map(v=>`<a href="${link({view:v,sort:'',direction:'desc'})}" class="${state.view===v?'active':''}" ${state.view===v?'aria-current="page"':''}>${v==='traditional'&&detail?'Standard':label(v)}</a>`).join('')}</nav>${segmentControl()}</div>`;}
function filters(count){const data=current();const positions=[...new Set(data.players.filter(r=>r.level==='SEASON').flatMap(r=>r.position.split(',')))].sort();return `<div class="filters"><label class="sr-only" for="team">Team</label><select id="team"><option value="">All Teams</option>${data.teams.map(t=>`<option value="${esc(t.id)}" ${state.team===t.id?'selected':''}>${esc(t.id)} · ${esc(t.name)}</option>`).join('')}</select>${state.category!=='teams'?`<label class="sr-only" for="position">Position</label><select id="position"><option value="">All positions</option>${positions.map(p=>`<option ${state.position===p?'selected':''}>${esc(p)}</option>`).join('')}</select>`:''}<label class="sr-only" for="search">Search ${state.category==='teams'?'teams':'players'}</label><input id="search" type="search" autocomplete="off" placeholder="Search ${state.category==='teams'?'teams':'players'}…" value="${esc(state.search)}"><span class="results-count" aria-live="polite">${count} ${state.category==='teams'?(count===1?'team':'teams'):(count===1?'player':'players')}</span></div>`;}
function table(rows,cols,{history=false,stints=false,view=state.view}={}){const sort=state.sort||defaultSort(state.category,state.view);return `<div class="table-scroll" tabindex="0" role="region" aria-label="${history?'Season history':'Statistics table'}"><table><caption class="sr-only">${history?'Player season history':`${state.season} ${state.category} ${state.view} statistics`}</caption><thead><tr>${!history&&!stints?'<th class="rank" scope="col">RK</th>':''}${cols.map(col=>`<th scope="col" class="${col.type==='text'?'left':''} ${col.key==='name'?'identity-heading':''} ${col.key==='team'||col.key==='position'?'metadata-heading':''}" ${!history&&!stints?`aria-sort="${col.key===sort?(state.direction==='asc'?'ascending':'descending'):'none'}"`:''}>${history||stints?esc(col.label):`<button data-sort="${esc(col.key)}" title="${esc(description(col))}">${esc(col.label)}<span class="sort-mark" aria-hidden="true">${col.key===sort?(state.direction==='asc'?'▲':'▼'):'↕'}</span></button>`}</th>`).join('')}</tr></thead><tbody>${rows.map((row,i)=>`<tr data-id="${esc(row.id)}" data-team="${esc(row.team)}" data-level="${esc(row.level)}">${!history&&!stints?`<td class="rank">${i+1}</td>`:''}${cols.map(col=>{if(col.key==='season')return `<td class="metadata"><a class="history-link" href="${link({season:row.season,segment:'combined',team:''})}">${row.season}</a></td>`;const v=value(row,col.key,view);return `<td data-key="${col.key}" class="${col.key==='name'?'identity':col.type==='text'?'metadata':''} ${col.key===sort&&!history?'sorted':''} ${col.type==='signed'&&typeof v==='number'?(v>0?'positive':v<0?'negative':''):''}">${col.key==='name'&&state.category!=='teams'?`<a href="${link({player:row.id})}">${esc(row.name)}</a>`:esc(format(v,col.type))}</td>`;}).join('')}</tr>`).join('')}</tbody></table></div>`;}
function note(){if(state.view==='traditional')return state.category==='teams'?'Team PTS counts scoring points only. Assists are not added.':'PTS = goals + assists + the extra point for two-point goals.';if(state.category==='teams')return 'Efficiency is scoring points per 100 possessions. Pace and time of possession use measurable spans only.';if(state.category==='goalies')return 'Resolved events only. Coverage excludes unresolved outcomes from save rates. Saves above average does not isolate goalie skill.';if(state.category==='faceoffs')return 'Wins above the same-season league rate. Draw share uses team attempts during actual appearances.';return 'Shares reflect the games each player appeared in. A dash (—) means the statistic is unavailable. Open the stat key for definitions.';}
function listing(){const data=current();const cols=columns(state.category,state.view,state.segment);if(!cols.some(c=>c.key===state.sort))state.sort='';const rows=sortRows(selectRows(data,state),state.sort||defaultSort(state.category,state.view),state.view,state.direction);return `<div class="page-heading"><h1>PLL ${categoryTitle()} Stats ${state.season}</h1><p>${esc(segmentNames[state.segment])} <span aria-hidden="true">·</span> ${state.view==='advanced'?'Advanced statistics':'Season totals'}</p></div>${tabs()}${data.message?`<p class="note competition-note">${esc(data.message)}</p>`:''}${filters(rows.length)}<section id="results" class="stats-panel"><div class="table-heading"><h2>${categoryTitle()} statistics</h2><span>${esc(segmentNames[state.segment])}</span></div>${rows.length?table(rows,cols):`<div class="empty">${esc(data.message||'No matching statistics.')}<br>${data.status==='not_held'?'':'<button id="clear">Clear filters</button>'}</div>`}${statKey(cols)}</section>${state.team&&state.category!=='teams'?'<p class="note">Showing statistics earned while playing for the selected team.</p>':''}<p class="note">${esc(note())}</p>`;}

function statKey(cols){return `<details class="stat-key"><summary>Stat key</summary><dl>${cols.filter(c=>c.type!=='text').map(c=>`<div><dt>${esc(c.label)}</dt><dd>${esc(description(c))}</dd></div>`).join('')}</dl></details>`;}
function trend(history,identity){
 const goalie=identity.position.split(',').includes('G');
 const faceoff=identity.position.split(',').includes('FO')||state.category==='faceoffs';
 const key=goalie?'save_pct':faceoff?'faceoff_pct':state.view==='advanced'?'scoring_points_per_shot':'points';
 const title=goalie?'Save percentage':faceoff?'Faceoff win percentage':state.view==='advanced'?'Scoring points per shot':'Points';
 const type=goalie||faceoff?'pct':state.view==='advanced'?'decimal':'int';
 const series=[...history].reverse().map(r=>({year:r.season,value:r[state.view][key]??null}));
 const maximum=Math.max(0,...series.map(r=>r.value??0));
 return `<figure class="trend"><figcaption><h2>${title} by season</h2><span>Regular season + playoffs</span></figcaption><div class="trend-scale"><span>0</span><span>${esc(format(maximum,type))}</span></div><ol>${series.map(r=>`<li data-season="${r.year}" data-metric="${key}" data-value="${r.value??''}"><span class="trend-year">${r.year}</span><span class="trend-track" aria-hidden="true"><span style="width:${r.value===null||!maximum?0:100*r.value/maximum}%"></span></span><strong>${esc(format(r.value,type))}</strong></li>`).join('')}</ol><p>Games played may differ by season.${state.view==='traditional'&&key==='points'?' Includes assists and two-point goals.':''}</p></figure>`;
}

function strip(row,cols,view){return `<dl class="stat-strip ${view==='advanced'?'advanced-strip':''}">${cols.map(col=>`<div class="stat" title="${esc(description(col))}"><dt>${col.label}</dt><dd data-key="${col.key}">${esc(format(row[view][col.key],col.type))}</dd></div>`).join('')}</dl>`;}
function detail(){const row=playerSeason(current(),state.player);const history=seasons.map(y=>playerSeason(store.years[y],state.player)).filter(Boolean);const identity=row||history[0];if(!identity)return `<div class="detail-empty">Player not found. <a class="back" href="${link({player:''})}">Back to statistics</a></div>`;const head=`<div class="detail-head"><a class="back" href="${link({player:''})}">← Back to statistics</a><h1>${esc(identity.name)}</h1><div class="detail-meta">${row?esc(row.teams.join(' / '))+' &nbsp; · &nbsp; '+esc(row.position)+' &nbsp; · &nbsp; '+state.season+' · '+esc(segmentNames[state.segment]):'No eligible appearance in '+state.season}${row&&row.teams.length>1?' &nbsp; · &nbsp; Season total':''}</div></div>${tabs(true)}`;let content='';if(!row)content=`<p class="note">${esc(current().message||'No appearances in this competition. Choose another competition or season.')}</p>`;else if(state.view==='traditional')content=strip(row,traditionalStrip,'traditional');else content=roleSections(row).map(([title,cols])=>`<section class="detail-section"><h2 class="eyebrow">${label(title)}</h2>${strip(row,cols,'advanced')}</section>`).join('')+`<p class="note">${row.position.includes('G')?'Saves above average reflects observed outcomes, not isolated goalie skill.':row.position.match(/D|LSM/)?'Descriptive production only; minutes, matchups and on/off information are unavailable.':'Descriptive season results, not persistent talent or a composite player score.'} Unavailable statistics appear as —.</p>`;
 const hc=[{key:'season',label:'SEASON',type:'text'},{key:'team',label:'TEAM',type:'text'},...(state.view==='advanced'?[...new Map(roleSections(identity).flatMap(([,cols])=>cols).map(c=>[c.key,c])).values()]:traditionalStrip)];
 if(history.length>1)content+=trend(history,identity);
 if(row&&current().message)content=`<p class="note competition-note">${esc(current().message)}</p>`+content;
 content+=`<section class="detail-section" id="results"><h2 class="eyebrow">Season stats <span class="scope-note">Regular season + playoffs</span></h2>${table(history,hc,{history:true})}</section>`;
 if(row&&row.teams.length>1){const splits=current().players.filter(r=>r.id===row.id&&r.level==='STINT');content+=`<section class="detail-section"><h2 class="eyebrow">${state.season} team splits <span class="scope-note">Included in season total above</span></h2>${table(splits,hc.filter(c=>c.key!=='season'),{stints:true})}</section>`;}
 return `<div class="detail">${head}${content}</div>`;}
function footer(){return `<footer><span>Source: <a href="https://premierlacrosseleague.com" target="_blank" rel="noreferrer">Premier Lacrosse League</a> · Independent analytics</span><span>${esc(segmentNames[state.segment])}${splitSeasons.includes(state.season)&&['regular','post'].includes(state.segment)?` · Above-expected metrics use the ${state.season} regular-season baseline`:''}${state.segment==='post'?' · Small playoff samples':''}${state.segment==='champ_series'&&state.season>=2023?' · Sixes-only tournament baseline · Possession metrics unavailable':''}</span></footer>`;}
function render(){if(!store)return;const input=document.activeElement?.id==='search';const caret=input?document.activeElement.selectionStart:null;app.innerHTML=`<div class="shell">${header()}</div><main>${state.player?detail():listing()}${footer()}</main>`;document.title=`${state.player?(playerSeason(current(),state.player)?.name||'Player'):label(state.category)} · ${state.season} · PLL Stats`;bind();if(input){const el=document.querySelector('#search');el?.focus();if(caret!==null)el?.setSelectionRange?.(caret,caret);}}
function update(changes,replace=false){state={...state,...changes};const next=route(state);if(replace){history.replaceState(null,'',next);render();}else if(location.hash===next)render();else location.hash=next;}
function bind(){document.querySelector('#season').onchange=e=>{const year=Number(e.target.value);update({season:year,segment:splitSeasons.includes(year)?'regular':'combined',team:store.years[year].teams.some(t=>t.id===state.team)?state.team:''});};document.querySelector('#segment')?.addEventListener('change',e=>update({segment:e.target.value,team:'',sort:''}));for(const key of ['team','position']){const el=document.querySelector('#'+key);if(el)el.onchange=e=>update({[key]:e.target.value});}const search=document.querySelector('#search');if(search)search.oninput=e=>update({search:e.target.value},true);document.querySelector('#clear')?.addEventListener('click',()=>update({team:'',position:'',search:''}));document.querySelectorAll('[data-sort]').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.sort;const active=state.sort||defaultSort(state.category,state.view);update({sort:key,direction:key===active?(state.direction==='desc'?'asc':'desc'):['name','team','position'].includes(key)?'asc':'desc'});}));}
window.addEventListener('hashchange',()=>{state=readState(location.hash);render();});
async function start(){try{store=await loadData();render();}catch(error){app.innerHTML='<div class="loading" role="alert">Statistics could not be loaded. Build the local data bundle and try again. <button id="retry">Retry</button></div>';document.querySelector('#retry').onclick=start;}}
start();
