import {seasons,categories,readState,route,loadData,selectRows,sortRows,value,format,defaultSort,playerSeason,metricDescription} from './data.js';
import {columns,traditionalStrip,roleSections} from './columns.js';
const app=document.querySelector('#app');let store;let state=readState(location.hash);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(changes)=>esc(route({...state,...changes}));
const label=c=>c.toUpperCase();
function description(col){if(state.view==='traditional')return col.description||`Official box-score ${col.label}; rates use pooled official counts.`;const m=store.metadata[col.key];return col.description||(m?metricDescription(m):'Official box-score '+col.label);}
function header(){return `<header><a class="brand" href="#/players?season=2026&view=traditional" aria-label="PLL Stats home">PLL STATS</a><div class="season-group"><span class="partial" title="Frozen snapshot; latest included game starts August 30, 2026 at 00:30 UTC">${state.season===2026&&state.category==='teams'&&!state.player?'PARTIAL SEASON':''}</span><label class="sr-only" for="season">Season</label><select id="season">${seasons.map(y=>`<option ${y===state.season?'selected':''}>${y}</option>`).join('')}</select></div></header><nav class="primary" aria-label="Statistics categories">${categories.map(c=>`<a href="${link({category:c,player:'',sort:'',direction:'desc',position:'',search:''})}" class="${c===state.category?'active':''}" ${c===state.category?'aria-current="page"':''}>${label(c)}</a>`).join('')}</nav>`;}
function tabs(detail=false){return `<nav class="secondary" aria-label="Statistic type">${['traditional','advanced'].map(v=>`<a href="${link({view:v,sort:'',direction:'desc'})}" class="${state.view===v?'active':''}" ${state.view===v?'aria-current="page"':''}>${v==='traditional'&&detail?'STATS':label(v)}</a>`).join('')}</nav>`;}
function filters(count){const data=store.years[state.season];const positions=[...new Set(data.players.filter(r=>r.level==='SEASON').flatMap(r=>r.position.split(',')))].sort();return `<div class="filters"><label class="sr-only" for="team">Team</label><select id="team"><option value="">All Teams</option>${data.teams.map(t=>`<option value="${esc(t.id)}" ${state.team===t.id?'selected':''}>${esc(t.id)} · ${esc(t.name)}</option>`).join('')}</select>${state.category!=='teams'?`<label class="sr-only" for="position">Position</label><select id="position"><option value="">All Pos</option>${positions.map(p=>`<option ${state.position===p?'selected':''}>${esc(p)}</option>`).join('')}</select>`:''}<label class="sr-only" for="search">Search ${state.category==='teams'?'teams':'players'}</label><input id="search" type="search" autocomplete="off" placeholder="Search ${state.category==='teams'?'teams':'players'}…" value="${esc(state.search)}"><span class="results-count" aria-live="polite">${count} ${count===1?'result':'results'}</span></div>`;}
function table(rows,cols,{history=false,stints=false,view=state.view}={}){const sort=state.sort||defaultSort(state.category,state.view);return `<div class="table-scroll" tabindex="0" role="region" aria-label="${history?'Season history':'Statistics table'}"><table><caption class="sr-only">${history?'Player season history':`${state.season} ${state.category} ${state.view} statistics`}</caption><thead><tr>${!history&&!stints?'<th class="rank" scope="col">RK</th>':''}${cols.map(col=>`<th scope="col" class="${col.type==='text'?'left':''}" ${!history&&!stints?`aria-sort="${col.key===sort?(state.direction==='asc'?'ascending':'descending'):'none'}"`:''}>${history||stints?esc(col.label):`<button data-sort="${esc(col.key)}" title="${esc(description(col))}">${esc(col.label)}<span class="sort-mark" aria-hidden="true">${col.key===sort?(state.direction==='asc'?'▲':'▼'):'↕'}</span></button>`}</th>`).join('')}</tr></thead><tbody>${rows.map((row,i)=>`<tr data-id="${esc(row.id)}" data-team="${esc(row.team)}" data-level="${esc(row.level)}">${!history&&!stints?`<td class="rank">${String(i+1).padStart(2,'0')}</td>`:''}${cols.map(col=>{if(col.key==='season')return `<td class="metadata"><a class="history-link" href="${link({season:row.season,team:''})}">${row.season}</a></td>`;const v=value(row,col.key,view);return `<td data-key="${col.key}" class="${col.key==='name'?'identity':col.type==='text'?'metadata':''} ${col.key===sort&&!history?'sorted':''}">${col.key==='name'&&state.category!=='teams'?`<a href="${link({player:row.id})}">${esc(row.name)}</a>`:esc(format(v,col.type))}</td>`;}).join('')}</tr>`).join('')}</tbody></table></div>`;}
function note(){if(state.view==='traditional')return state.category==='teams'?'Official team box-score totals. PTS is PLL scoring points; assists are not added.':'Official box-score totals. Player PTS includes official assists and the extra point for 2PT goals.';if(state.category==='teams')return 'Efficiency: PLL points per 100 possessions. Pace and TOP use measurable spans only; hover for definitions.';if(state.category==='goalies')return 'Resolved events only. Coverage excludes unresolved outcomes from save rates. Saves above average does not isolate goalie skill.';if(state.category==='faceoffs')return 'Wins above the same-season league rate. Draw share uses team attempts during actual appearances.';return 'Same-season descriptive metrics. Shares use actual appearances; — means undefined, not zero. Hover column labels for definitions.';}
function listing(){const data=store.years[state.season];const cols=columns(state.category,state.view);if(!cols.some(c=>c.key===state.sort))state.sort='';const rows=sortRows(selectRows(data,state),state.sort||defaultSort(state.category,state.view),state.view,state.direction);return `${tabs()}${filters(rows.length)}<section id="results"><h1 class="eyebrow">${label(state.category)} STATISTICS — ${label(state.view)}</h1>${rows.length?table(rows,cols):'<div class="empty">No matching statistics.<br><button id="clear">Clear filters</button></div>'}</section>${state.team&&state.category!=='teams'?'<p class="note">Team filter: showing only production in that team’s stint, not full-season totals.</p>':''}<p class="note">${esc(note())}</p>`;}
function strip(row,cols,view){return `<dl class="stat-strip ${view==='advanced'?'advanced-strip':''}">${cols.map(col=>`<div class="stat" title="${esc(description(col))}"><dt>${col.label}</dt><dd data-key="${col.key}">${esc(format(row[view][col.key],col.type))}</dd></div>`).join('')}</dl>`;}
function detail(){const row=playerSeason(store.years[state.season],state.player);const history=seasons.map(y=>playerSeason(store.years[y],state.player)).filter(Boolean);const identity=row||history[0];if(!identity)return `<div class="detail-empty">Player not found. <a class="back" href="${link({player:''})}">Back to statistics</a></div>`;const head=`<div class="detail-head"><a class="back" href="${link({player:''})}">← Back to statistics</a><h1>${esc(identity.name)}</h1><div class="detail-meta">${row?esc(row.teams.join(' / '))+' &nbsp; · &nbsp; '+esc(row.position)+' &nbsp; · &nbsp; '+state.season:'No eligible appearance in '+state.season}${row&&row.teams.length>1?' &nbsp; · &nbsp; Season total':''}</div></div>${tabs(true)}`;let content='';if(!row)content='<p class="note">No statistics for this season. Choose a season from the history below.</p>';else if(state.view==='traditional')content=strip(row,traditionalStrip,'traditional');else content=roleSections(row).map(([title,cols])=>`<section class="detail-section"><h2 class="eyebrow">${title}</h2>${strip(row,cols,'advanced')}</section>`).join('')+`<p class="note">${row.position.includes('G')?'Saves above average reflects observed outcomes, not isolated goalie skill.':row.position.match(/D|LSM/)?'Descriptive production only; minutes, matchups and on/off information are unavailable.':'Descriptive season results, not persistent talent or a composite player score.'} Undefined values appear as —.</p>`;
 const hc=[{key:'season',label:'SEASON',type:'text'},{key:'team',label:'TEAM',type:'text'},...(state.view==='advanced'?[...new Map(roleSections(identity).flatMap(([,cols])=>cols).map(c=>[c.key,c])).values()]:traditionalStrip)];
 content+=`<section class="detail-section" id="results"><h2 class="eyebrow">SEASON HISTORY <span class="scope-note">Season totals</span></h2>${table(history,hc,{history:true})}</section>`;
 if(row&&row.teams.length>1){const splits=store.years[state.season].players.filter(r=>r.id===row.id&&r.level==='STINT');content+=`<section class="detail-section"><h2 class="eyebrow">${state.season} TEAM SPLITS <span class="scope-note">Included in season total above</span></h2>${table(splits,hc.filter(c=>c.key!=='season'),{stints:true})}</section>`;}
 return `<div class="detail">${head}${content}</div>`;}
function footer(){return `<footer><span>Source: <a href="https://premierlacrosseleague.com" target="_blank" rel="noreferrer">Premier Lacrosse League</a> · Independent analytics</span><span>Regular season + playoffs${state.season===2026?' · Frozen through Aug 30, 2026':''}</span></footer>`;}
function render(){if(!store)return;const input=document.activeElement?.id==='search';const caret=input?document.activeElement.selectionStart:null;app.innerHTML=`<div class="shell">${header()}</div><main>${state.player?detail():listing()}${footer()}</main>`;document.title=`${state.player?(playerSeason(store.years[state.season],state.player)?.name||'Player'):label(state.category)} · ${state.season} · PLL Stats`;bind();if(input){const el=document.querySelector('#search');el?.focus();if(caret!==null)el?.setSelectionRange?.(caret,caret);}}
function update(changes,replace=false){state={...state,...changes};const next=route(state);if(replace){history.replaceState(null,'',next);render();}else if(location.hash===next)render();else location.hash=next;}
function bind(){document.querySelector('#season').onchange=e=>{const year=Number(e.target.value);update({season:year,team:store.years[year].teams.some(t=>t.id===state.team)?state.team:''});};for(const key of ['team','position']){const el=document.querySelector('#'+key);if(el)el.onchange=e=>update({[key]:e.target.value});}const search=document.querySelector('#search');if(search)search.oninput=e=>update({search:e.target.value},true);document.querySelector('#clear')?.addEventListener('click',()=>update({team:'',position:'',search:''}));document.querySelectorAll('[data-sort]').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.sort;const active=state.sort||defaultSort(state.category,state.view);update({sort:key,direction:key===active?(state.direction==='desc'?'asc':'desc'):['name','team','position'].includes(key)?'asc':'desc'});}));}
window.addEventListener('hashchange',()=>{state=readState(location.hash);render();});
async function start(){try{store=await loadData();render();}catch(error){app.innerHTML='<div class="loading" role="alert">Statistics could not be loaded. Build the local data bundle and try again. <button id="retry">Retry</button></div>';document.querySelector('#retry').onclick=start;}}
start();
