// All advanced keys are copied from the final publication layer.
const c=(key,label,type='int',description='')=>({key,label,type,description});
const player=[c('name','PLAYER','text'),c('team','TEAM','text')];
const shooting=[c('goals','G'),c('twoPointGoals','2PTG'),c('assists','A'),c('points','PTS','int','Official player points: one-point goals + twice two-point goals + official assists.'),c('shots','SH'),c('shotsOnGoal','SOG'),c('shooting_pct','SH%','pct')];
export const traditionalStrip=[c('games_played','GP'),...shooting,c('groundBalls','GB'),c('causedTurnovers','CT'),c('turnovers','TO')];
export const offenseAdvanced=[c('shooting_pct','SH%','pct'),c('shots_on_goal_pct','SOG%','pct'),c('scoring_points_per_shot','PTS/SHOT','decimal'),c('shooting_value_above_expected','SVAE','signed'),c('shot_share','SHOT SHARE','pct'),c('two_point_attempt_rate','2PT ATT%','pct'),c('two_point_conversion_pct','2PT CONV%','pct'),c('two_point_shooting_value','2PT VALUE','signed'),c('team_two_point_attempt_share','TEAM 2PT SHARE','pct'),c('turnovers_per_touch','TO/TOUCH','ratio'),c('turnovers_below_expected','TO BELOW EXP','signed')];
export const goalieAdvanced=[c('save_pct','SAVE%','pct'),c('one_point_save_pct','1PT SAVE%','pct'),c('two_point_save_pct','2PT SAVE%','pct'),c('saves_above_average','SAVES ABOVE AVG','signed'),c('resolved_shots_faced','RESOLVED SOG'),c('resolved_coverage','COVERAGE','pct','Resolved saves and goals / all recorded on-goal outcomes. Unresolved outcomes are excluded from save rates.')];
export const faceoffAdvanced=[c('faceoff_pct','FO%','pct'),c('draw_share','DRAW SHARE','pct'),c('faceoff_wins_above_average','FO WINS ABOVE AVG','signed')];
export const defenseAdvanced=[c('caused_turnovers_per_game','CT/G','decimal'),c('ground_balls_per_game','GB/G','decimal'),c('penalties_per_game','PEN/G','decimal')];
export const teamAdvanced=[c('name','TEAM','text'),c('offensive_efficiency','OFF EFF','decimal'),c('defensive_efficiency','DEF EFF','decimal'),c('net_efficiency','NET','signed'),c('shots_per_possession','SH/POSS','ratio'),c('turnovers_per_possession','TO/POSS','ratio'),c('shot_clock_expirations_per_possession','SHOT CLOCK/POSS','ratio'),c('shot_producing_possession_rate','SHOT PROD%','pct'),c('multi_shot_possession_rate','MULTI-SHOT%','pct'),c('offensive_pace_seconds','OFF PACE','seconds'),c('defensive_pace_seconds','DEF PACE','seconds'),c('time_of_possession_share','TOP%','pct'),c('team_assist_to_goal_ratio','AST/G','ratio')];
export function columns(category,view){
 if(category==='teams')return view==='advanced'?teamAdvanced:[c('name','TEAM','text'),c('games_played','GP'),...shooting.filter(x=>x.key!=='shooting_pct').map(x=>x.key==='points'?c('points','PTS','int','Official team scoring points; assists are not added.'):x),c('groundBalls','GB'),c('turnovers','TO'),c('faceoff_pct','FO%','pct'),c('save_pct','SV%','pct'),c('numPenalties','PEN')];
 if(category==='goalies')return [...player,...(view==='advanced'?goalieAdvanced:[c('games_played','GP'),c('saves','SAVES'),c('goalsAgainst','GOALS ALLOWED'),c('save_pct','SAVE%','pct')])];
 if(category==='faceoffs')return [...player,...(view==='advanced'?faceoffAdvanced:[c('games_played','GP'),c('faceoffsWon','FO W'),c('faceoffs','FO ATT'),c('faceoff_pct','FO%','pct')])];
 return [...player,c('position','POS','text'),...(view==='advanced'?offenseAdvanced.filter(x=>!['shooting_pct','shots_on_goal_pct','team_two_point_attempt_share'].includes(x.key)):traditionalStrip)];
}
export function roleSections(row){const positions=row.position.split(',');const groups=[];if(positions.some(p=>['A','M'].includes(p)))groups.push(['OFFENSE',offenseAdvanced]);if(positions.includes('FO'))groups.push(['FACEOFF',faceoffAdvanced]);if(positions.includes('G'))groups.push(['GOALKEEPING',goalieAdvanced]);if(positions.some(p=>['D','LSM','SSDM'].includes(p)))groups.push(['DEFENSIVE PRODUCTION',defenseAdvanced]);if(!groups.length)groups.push(['OBSERVED PRODUCTION',defenseAdvanced]);return groups;}
