"""Frozen final metric metadata. No statistical calculations occur here."""
import csv
from pathlib import Path
DEFINITIONS = [{'metric_name': 'possessions_per_game',
  'display_name': 'Possessions Per Game',
  'category': 'TEAM',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'TEAM',
  'formula': '(possessions) / (games_played)',
  'numerator': 'possessions',
  'denominator': 'games_played',
  'unit': 'possessions/game',
  'interpretation': 'Reconstructed team pace; regulation and overtime combined.',
  'direction': 'descriptive',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/possessions.csv; events.csv; '
                         'team_game_stats.csv; games.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Reconstructed team pace; regulation and overtime combined.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'team_advanced_stats',
  'output_column': 'possessions_per_game'},
 {'metric_name': 'offensive_efficiency',
  'display_name': 'Offensive Efficiency',
  'category': 'TEAM',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'TEAM',
  'formula': '(100 * points) / (possessions)',
  'numerator': '100 * points',
  'denominator': 'possessions',
  'unit': 'PLL points/100 possessions',
  'interpretation': 'Points produced on reconstructed offensive possessions.',
  'direction': 'higher_is_better',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/possessions.csv; events.csv; '
                         'team_game_stats.csv; games.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Points produced on reconstructed offensive possessions.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'team_advanced_stats',
  'output_column': 'offensive_efficiency'},
 {'metric_name': 'defensive_efficiency',
  'display_name': 'Defensive Efficiency',
  'category': 'TEAM',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'TEAM',
  'formula': '(100 * points_allowed) / (defensive_possessions)',
  'numerator': '100 * points_allowed',
  'denominator': 'defensive_possessions',
  'unit': 'PLL points/100 possessions',
  'interpretation': 'Points allowed on reconstructed defensive possessions.',
  'direction': 'lower_is_better',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/possessions.csv; events.csv; '
                         'team_game_stats.csv; games.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Points allowed on reconstructed defensive possessions.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'team_advanced_stats',
  'output_column': 'defensive_efficiency'},
 {'metric_name': 'net_efficiency',
  'display_name': 'Net Efficiency',
  'category': 'TEAM',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'TEAM',
  'formula': 'offensive_efficiency - defensive_efficiency',
  'numerator': 'offensive_efficiency - defensive_efficiency',
  'denominator': 'not applicable',
  'unit': 'PLL points/100 possessions',
  'interpretation': 'Difference between team scoring and conceding rates.',
  'direction': 'higher_is_better',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/possessions.csv; events.csv; '
                         'team_game_stats.csv; games.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Difference between team scoring and conceding rates.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'team_advanced_stats',
  'output_column': 'net_efficiency'},
 {'metric_name': 'shots_per_possession',
  'display_name': 'Shots Per Possession',
  'category': 'TEAM',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'TEAM',
  'formula': '(shots) / (possessions)',
  'numerator': 'shots',
  'denominator': 'possessions',
  'unit': 'attempts/possession',
  'interpretation': 'Shot generation per reconstructed possession.',
  'direction': 'descriptive',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/possessions.csv; events.csv; '
                         'team_game_stats.csv; games.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Shot generation per reconstructed possession.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'team_advanced_stats',
  'output_column': 'shots_per_possession'},
 {'metric_name': 'turnovers_per_possession',
  'display_name': 'Turnovers Per Possession',
  'category': 'TEAM',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'TEAM',
  'formula': '(official_turnovers) / (possessions)',
  'numerator': 'official_turnovers',
  'denominator': 'possessions',
  'unit': 'turnovers/possession',
  'interpretation': 'Official team turnovers per reconstructed possession, including team-only turnovers.',
  'direction': 'lower_is_better',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/possessions.csv; events.csv; '
                         'team_game_stats.csv; games.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Official team turnovers per reconstructed possession, including team-only turnovers.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'team_advanced_stats',
  'output_column': 'turnovers_per_possession'},
 {'metric_name': 'shot_clock_expirations_per_possession',
  'display_name': 'Shot Clock Expirations Per Possession',
  'category': 'TEAM',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'TEAM',
  'formula': '(shot_clock_events) / (possessions)',
  'numerator': 'shot_clock_events',
  'denominator': 'possessions',
  'unit': 'expirations/possession',
  'interpretation': 'Frequency of logged shot-clock expiration events.',
  'direction': 'lower_is_better',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/possessions.csv; events.csv; '
                         'team_game_stats.csv; games.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Frequency of logged shot-clock expiration events.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'team_advanced_stats',
  'output_column': 'shot_clock_expirations_per_possession'},
 {'metric_name': 'offensive_pace_seconds',
  'display_name': 'Offensive Pace Seconds',
  'category': 'TEAM',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'TEAM',
  'formula': '(measurable_possession_seconds) / (measurable_possessions)',
  'numerator': 'measurable_possession_seconds',
  'denominator': 'measurable_possessions',
  'unit': 'seconds',
  'interpretation': 'Average observed span, restricted to measurable boundaries; not full possession duration.',
  'direction': 'descriptive',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/possessions.csv; events.csv; '
                         'team_game_stats.csv; games.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Unambiguous, nontruncated, distinct-event spans only; observed subset is not total possession '
                        'time. Show measurable coverage.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'team_advanced_stats',
  'output_column': 'offensive_pace_seconds'},
 {'metric_name': 'median_possession_span',
  'display_name': 'Median Possession Span',
  'category': 'TEAM',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'TEAM',
  'formula': 'median duration_seconds over measurable possessions',
  'numerator': 'median duration_seconds over measurable possessions',
  'denominator': 'not applicable',
  'unit': 'seconds',
  'interpretation': 'Median observed span over the same subset; less sensitive to long spans.',
  'direction': 'descriptive',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/possessions.csv; events.csv; '
                         'team_game_stats.csv; games.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Unambiguous, nontruncated, distinct-event spans only; observed subset is not total possession '
                        'time. Show measurable coverage.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'team_advanced_stats',
  'output_column': 'median_possession_span'},
 {'metric_name': 'shooting_pct',
  'display_name': 'Shooting Pct',
  'category': 'OFFENSE',
  'classification': 'STANDARD',
  'catalog_status': 'CORE',
  'level': 'PLAYER',
  'formula': '(g1 + g2) / (shots)',
  'numerator': 'g1 + g2',
  'denominator': 'shots',
  'unit': 'proportion',
  'interpretation': 'Conversion of all logged attempts into goals, independent of point value.',
  'direction': 'higher_is_better',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/events.csv; player_game_stats.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Conversion of all logged attempts into goals, independent of point value.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'player_shooting_advanced',
  'output_column': 'shooting_pct'},
 {'metric_name': 'shots_on_goal_pct',
  'display_name': 'Shots On Goal Pct',
  'category': 'OFFENSE',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'PLAYER',
  'formula': '(sog) / (shots)',
  'numerator': 'sog',
  'denominator': 'shots',
  'unit': 'proportion',
  'interpretation': 'Share of logged attempts classified as on goal; retain unresolved on-goal class count.',
  'direction': 'higher_is_better',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/events.csv; player_game_stats.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Share of logged attempts classified as on goal; retain unresolved on-goal class count.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'player_shooting_advanced',
  'output_column': 'shots_on_goal_pct'},
 {'metric_name': 'scoring_points_per_shot',
  'display_name': 'PLL Points per Shot',
  'category': 'OFFENSE',
  'classification': 'PLL_SPECIFIC_ADAPTATION',
  'catalog_status': 'CORE',
  'level': 'PLAYER',
  'formula': '(g1 + 2*g2) / (shots)',
  'numerator': 'g1 + 2*g2',
  'denominator': 'shots',
  'unit': 'PLL scoring points/attempt',
  'interpretation': 'Scoring return on shots. Assists excluded; traditional player points are a separate context '
                    'field.',
  'direction': 'higher_is_better',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/events.csv; player_game_stats.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Scoring return on shots. Assists excluded; traditional player points are a separate context '
                        'field.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'player_shooting_advanced',
  'output_column': 'scoring_points_per_shot'},
 {'metric_name': 'turnovers_per_touch',
  'display_name': 'Turnovers Per Touch',
  'category': 'OFFENSE',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'PLAYER',
  'formula': '(turnovers) / (touches)',
  'numerator': 'turnovers',
  'denominator': 'touches',
  'unit': 'turnovers/touch proxy',
  'interpretation': 'Recorded ball security per feed touch count; not passing value.',
  'direction': 'lower_is_better',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/events.csv; player_game_stats.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Recorded ball security per feed touch count; not passing value.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'player_offensive_advanced',
  'output_column': 'turnovers_per_touch'},
 {'metric_name': 'turnovers_below_expected',
  'display_name': 'Turnovers Below Expected',
  'category': 'OFFENSE',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'PLAYER',
  'formula': 'touches * league_turnover_per_touch - turnovers',
  'numerator': 'touches * league_turnover_per_touch - turnovers',
  'denominator': 'not applicable; touches > 0',
  'unit': 'turnover events',
  'interpretation': 'Recorded turnovers avoided relative to a season league touch baseline; positive means fewer '
                    'turnovers.',
  'direction': 'higher_is_better',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/events.csv; player_game_stats.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Recorded turnovers avoided relative to a season league touch baseline; positive means fewer '
                        'turnovers.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'player_offensive_advanced',
  'output_column': 'turnovers_below_expected'},
 {'metric_name': 'shooting_value_above_expected',
  'display_name': 'Shooting Value Above Expected',
  'category': 'OFFENSE',
  'classification': 'PLL_SPECIFIC_ADAPTATION',
  'catalog_status': 'CORE',
  'level': 'PLAYER',
  'formula': 'g1 + 2*g2 - a1*p1 - 2*a2*p2',
  'numerator': 'g1 + 2*g2 - a1*p1 - 2*a2*p2',
  'denominator': 'not applicable; shots > 0',
  'unit': 'PLL scoring points',
  'interpretation': 'Scoring above season-average conversion on the same 1PT/2PT shot mix; no total-offense claim.',
  'direction': 'higher_is_better',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/events.csv; player_game_stats.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Scoring above season-average conversion on the same 1PT/2PT shot mix; no total-offense claim.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'player_shooting_advanced',
  'output_column': 'shooting_value_above_expected'},
 {'metric_name': 'two_point_attempt_rate',
  'display_name': 'Two Point Attempt Rate',
  'category': 'PLL_2PT',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'PLAYER',
  'formula': '(a2) / (shots)',
  'numerator': 'a2',
  'denominator': 'shots',
  'unit': 'proportion',
  'interpretation': 'Shot selection: frequency of choosing the two-point shot.',
  'direction': 'descriptive',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/events.csv; player_game_stats.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Shot selection: frequency of choosing the two-point shot.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'player_two_point_stats',
  'output_column': 'two_point_attempt_rate'},
 {'metric_name': 'two_point_conversion_pct',
  'display_name': 'Two Point Conversion Pct',
  'category': 'PLL_2PT',
  'classification': 'STANDARD',
  'catalog_status': 'CORE',
  'level': 'PLAYER',
  'formula': '(g2) / (a2)',
  'numerator': 'g2',
  'denominator': 'a2',
  'unit': 'proportion',
  'interpretation': 'Observed two-point conversion; not persistent shooting ability.',
  'direction': 'higher_is_better',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/events.csv; player_game_stats.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Observed two-point conversion; not persistent shooting ability.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'player_two_point_stats',
  'output_column': 'two_point_conversion_pct'},
 {'metric_name': 'two_point_shooting_value',
  'display_name': 'Two Point Shooting Value',
  'category': 'PLL_2PT',
  'classification': 'PLL_SPECIFIC_ADAPTATION',
  'catalog_status': 'CORE',
  'level': 'PLAYER',
  'formula': '2 * (g2 - a2*p2)',
  'numerator': '2 * (g2 - a2*p2)',
  'denominator': 'not applicable; a2 > 0',
  'unit': 'PLL scoring points',
  'interpretation': 'The two-point component of shooting value; never add it again to total shooting value.',
  'direction': 'higher_is_better',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/events.csv; player_game_stats.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'The two-point component of shooting value; never add it again to total shooting value.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'player_two_point_stats',
  'output_column': 'two_point_shooting_value'},
 {'metric_name': 'team_two_point_attempt_share',
  'display_name': 'Team Two Point Attempt Share',
  'category': 'PLL_2PT',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'PLAYER',
  'formula': '(a2) / (team_a2_in_appearances)',
  'numerator': 'a2',
  'denominator': 'team_a2_in_appearances',
  'unit': 'proportion',
  'interpretation': 'Share of team two-point attempts in the games the player appeared, respecting actual team in each '
                    'game.',
  'direction': 'descriptive',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/events.csv; player_game_stats.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Share of team two-point attempts in the games the player appeared, respecting actual team in '
                        'each game.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'player_two_point_stats',
  'output_column': 'team_two_point_attempt_share'},
 {'metric_name': 'faceoff_pct',
  'display_name': 'Faceoff Pct',
  'category': 'FACEOFF',
  'classification': 'STANDARD',
  'catalog_status': 'CORE',
  'level': 'PLAYER',
  'formula': '(faceoff_wins) / (faceoffs)',
  'numerator': 'faceoff_wins',
  'denominator': 'faceoffs',
  'unit': 'proportion',
  'interpretation': 'Observed faceoff success with attempts and unassigned outcomes visible.',
  'direction': 'higher_is_better',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/events.csv; player_game_stats.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Observed faceoff success with attempts and unassigned outcomes visible.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'faceoff_advanced',
  'output_column': 'faceoff_pct'},
 {'metric_name': 'draw_share',
  'display_name': 'Draw Share',
  'category': 'FACEOFF',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'PLAYER',
  'formula': '(faceoffs) / (team_faceoffs_in_appearances)',
  'numerator': 'faceoffs',
  'denominator': 'team_faceoffs_in_appearances',
  'unit': 'proportion',
  'interpretation': 'Draw workload in appearances, following actual game team for transfers.',
  'direction': 'descriptive',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/events.csv; player_game_stats.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Draw workload in appearances, following actual game team for transfers.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'faceoff_advanced',
  'output_column': 'draw_share'},
 {'metric_name': 'faceoff_wins_above_average',
  'display_name': 'Faceoff Wins Above Average',
  'category': 'FACEOFF',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'PLAYER',
  'formula': 'faceoff_wins - faceoffs*league_faceoff_rate',
  'numerator': 'faceoff_wins - faceoffs*league_faceoff_rate',
  'denominator': 'not applicable; faceoffs > 0',
  'unit': 'faceoff wins',
  'interpretation': 'Additional wins relative to all recorded league faceoff takers in that season; no point '
                    'conversion.',
  'direction': 'higher_is_better',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/events.csv; player_game_stats.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Additional wins relative to all recorded league faceoff takers in that season; no point '
                        'conversion.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'faceoff_advanced',
  'output_column': 'faceoff_wins_above_average'},
 {'metric_name': 'save_pct',
  'display_name': 'Save Pct',
  'category': 'GOALIE',
  'classification': 'STANDARD',
  'catalog_status': 'CORE',
  'level': 'PLAYER',
  'formula': '(resolved_saves) / (resolved_shots_faced)',
  'numerator': 'resolved_saves',
  'denominator': 'resolved_shots_faced',
  'unit': 'proportion',
  'interpretation': 'Observed saves among resolved saves and goals allowed; shots-faced denominator is explicitly '
                    'resolved shots.',
  'direction': 'higher_is_better',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/events.csv; player_game_stats.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'Exclude on_goal_no_save from save denominators; expose unresolved_goalie_sog and '
                               'resolved_coverage',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Unobserved shot quality and defensive environment; resolved event outcomes only, not pure '
                        'skill.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'goalie_advanced',
  'output_column': 'save_pct'},
 {'metric_name': 'one_point_save_pct',
  'display_name': 'One Point Save Pct',
  'category': 'GOALIE',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'PLAYER',
  'formula': '(sv1) / (sv1 + ga1)',
  'numerator': 'sv1',
  'denominator': 'sv1 + ga1',
  'unit': 'proportion',
  'interpretation': 'Observed one-point stopping among resolved attributable events; show attribution coverage.',
  'direction': 'higher_is_better',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/events.csv; player_game_stats.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'Exclude on_goal_no_save from save denominators; expose unresolved_goalie_sog and '
                               'resolved_coverage',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Unobserved shot quality and defensive environment; resolved event outcomes only, not pure '
                        'skill.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'goalie_advanced',
  'output_column': 'one_point_save_pct'},
 {'metric_name': 'two_point_save_pct',
  'display_name': 'Two Point Save Pct',
  'category': 'GOALIE',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'PLAYER',
  'formula': '(sv2) / (sv2 + ga2)',
  'numerator': 'sv2',
  'denominator': 'sv2 + ga2',
  'unit': 'proportion',
  'interpretation': 'Observed two-point stopping among resolved attributable events; show coverage and small '
                    'denominator.',
  'direction': 'higher_is_better',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/events.csv; player_game_stats.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'Exclude on_goal_no_save from save denominators; expose unresolved_goalie_sog and '
                               'resolved_coverage',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Unobserved shot quality and defensive environment; resolved event outcomes only, not pure '
                        'skill.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'goalie_advanced',
  'output_column': 'two_point_save_pct'},
 {'metric_name': 'saves_above_average',
  'display_name': 'Saves Above Average',
  'category': 'GOALIE',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'PLAYER',
  'formula': 'resolved_saves - resolved_shots_faced*league_save_rate',
  'numerator': 'resolved_saves - resolved_shots_faced*league_save_rate',
  'denominator': 'not applicable; resolved_shots_faced > 0',
  'unit': 'saves',
  'interpretation': 'Saves above season league stopping results at the same resolved workload; not shot-quality '
                    'adjusted.',
  'direction': 'higher_is_better',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/events.csv; player_game_stats.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'Exclude on_goal_no_save from save denominators; expose unresolved_goalie_sog and '
                               'resolved_coverage',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Unobserved shot quality and defensive environment; resolved event outcomes only, not pure '
                        'skill.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'goalie_advanced',
  'output_column': 'saves_above_average'},
 {'metric_name': 'caused_turnovers_per_game',
  'display_name': 'Caused Turnovers Per Game',
  'category': 'DEFENSE',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'PLAYER',
  'formula': '(caused_turnovers) / (games_played)',
  'numerator': 'caused_turnovers',
  'denominator': 'games_played',
  'unit': 'events/game',
  'interpretation': 'Recorded disruption, without individual defensive exposure adjustment.',
  'direction': 'descriptive',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/events.csv; player_game_stats.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Descriptive counts per appearance; no minutes, lineups, matchups or comprehensive defensive '
                        'attribution.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'defensive_production',
  'output_column': 'caused_turnovers_per_game'},
 {'metric_name': 'ground_balls_per_game',
  'display_name': 'Ground Balls Per Game',
  'category': 'DEFENSE',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'PLAYER',
  'formula': '(ground_balls) / (games_played)',
  'numerator': 'ground_balls',
  'denominator': 'games_played',
  'unit': 'events/game',
  'interpretation': 'Recorded recoveries, including faceoff-related recoveries; no impact composite.',
  'direction': 'descriptive',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/events.csv; player_game_stats.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Descriptive counts per appearance; no minutes, lineups, matchups or comprehensive defensive '
                        'attribution.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'defensive_production',
  'output_column': 'ground_balls_per_game'},
 {'metric_name': 'penalties_per_game',
  'display_name': 'Penalties Per Game',
  'category': 'DEFENSE',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'PLAYER',
  'formula': '(penalties) / (games_played)',
  'numerator': 'penalties',
  'denominator': 'games_played',
  'unit': 'penalties/game',
  'interpretation': 'Penalty frequency per appearance, not per defensive possession or minute.',
  'direction': 'descriptive',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/events.csv; player_game_stats.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Descriptive counts per appearance; no minutes, lineups, matchups or comprehensive defensive '
                        'attribution.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'defensive_production',
  'output_column': 'penalties_per_game'},
 {'metric_name': 'shot_producing_possession_rate',
  'display_name': 'Shot Producing Possession Rate',
  'category': 'TEAM',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'TEAM',
  'formula': '(shot_producing_possessions) / (possessions)',
  'numerator': 'shot_producing_possessions',
  'denominator': 'possessions',
  'unit': 'proportion',
  'interpretation': 'Proportion of possessions with at least one recorded attempt.',
  'direction': 'descriptive',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/possessions.csv; events.csv; '
                         'team_game_stats.csv; games.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Proportion of possessions with at least one recorded attempt. Boundary ambiguity can change '
                        'allocation; see possession_sensitivity.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'team_advanced_stats',
  'output_column': 'shot_producing_possession_rate'},
 {'metric_name': 'multi_shot_possession_rate',
  'display_name': 'Multi Shot Possession Rate',
  'category': 'TEAM',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'TEAM',
  'formula': '(multi_shot_possessions) / (possessions)',
  'numerator': 'multi_shot_possessions',
  'denominator': 'possessions',
  'unit': 'proportion',
  'interpretation': 'Proportion of possessions with at least two attempts; not a rebound metric.',
  'direction': 'descriptive',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/possessions.csv; events.csv; '
                         'team_game_stats.csv; games.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Proportion of possessions with at least two attempts; not a rebound metric. Boundary '
                        'ambiguity can change allocation; see possession_sensitivity.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'team_advanced_stats',
  'output_column': 'multi_shot_possession_rate'},
 {'metric_name': 'team_assist_to_goal_ratio',
  'display_name': 'Team Assist To Goal Ratio',
  'category': 'TEAM',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'TEAM',
  'formula': '(official_assists) / (official_goals)',
  'numerator': 'official_assists',
  'denominator': 'official_goals',
  'unit': 'proportion',
  'interpretation': 'Official assists per goal; two-point goals count once.',
  'direction': 'descriptive',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/possessions.csv; events.csv; '
                         'team_game_stats.csv; games.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Official assists per goal; two-point goals count once.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'team_advanced_stats',
  'output_column': 'team_assist_to_goal_ratio'},
 {'metric_name': 'time_of_possession_share',
  'display_name': 'Time Of Possession Share',
  'category': 'TEAM',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'TEAM',
  'formula': '(measurable_possession_seconds) / (team plus opponent measurable seconds in eligible team games)',
  'numerator': 'measurable_possession_seconds',
  'denominator': 'team plus opponent measurable seconds in eligible team games',
  'unit': 'proportion',
  'interpretation': 'Share of measured possession seconds in the team’s eligible games, not full game clock control.',
  'direction': 'descriptive',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/possessions.csv; events.csv; '
                         'team_game_stats.csv; games.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Unambiguous, nontruncated, distinct-event spans only; observed subset is not total possession '
                        'time. Show measurable coverage.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'team_advanced_stats',
  'output_column': 'time_of_possession_share'},
 {'metric_name': 'defensive_pace_seconds',
  'display_name': 'Defensive Pace Seconds',
  'category': 'TEAM',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'TEAM',
  'formula': '(defensive_measurable_seconds) / (defensive_measurable_possessions)',
  'numerator': 'defensive_measurable_seconds',
  'denominator': 'defensive_measurable_possessions',
  'unit': 'seconds',
  'interpretation': 'Mean measured opponent possession span, not defensive skill.',
  'direction': 'descriptive',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/possessions.csv; events.csv; '
                         'team_game_stats.csv; games.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Unambiguous, nontruncated, distinct-event spans only; observed subset is not total possession '
                        'time. Show measurable coverage.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'team_advanced_stats',
  'output_column': 'defensive_pace_seconds'},
 {'metric_name': 'shot_share',
  'display_name': 'Shot Share',
  'category': 'USAGE',
  'classification': 'DERIVED_ADVANCED',
  'catalog_status': 'CORE',
  'level': 'PLAYER',
  'formula': '(shots) / (team_shots_in_appearances)',
  'numerator': 'shots',
  'denominator': 'team_shots_in_appearances',
  'unit': 'proportion',
  'interpretation': 'Share of team shots during actual appearances; follows the actual team in each game.',
  'direction': 'descriptive',
  'source_population': 'Completed regular-season and playoff games; no all-star/exhibition. Same-season pooled '
                       'baselines including focal players. Actual appearances for players.',
  'source_files_tables': 'sql/publication.sql; data/processed/{season}/events.csv; player_game_stats.csv',
  'zero_denominator_behavior': 'NULL; surplus also NULL at zero exposure',
  'missing_data_behavior': 'Missing official inputs propagate NULL; absent eligible events are observed zero counts. '
                           'Named attribution mismatches stop build.',
  'unresolved_event_behavior': 'on_goal_no_save counts as SOG, not a goal or save; keep unresolved_sog where shooting '
                               'is used',
  'minimum_exposure': 'No inferential qualification. Display denominator; undefined metrics excluded from ordering. '
                      'Example filters are illustrative, not reliability thresholds.',
  'coverage_notes': '2022–2026 frozen eligible games; 2026 partial through 2026-08-30 00:30 UTC (latest game start).',
  'limitation_summary': 'Share of team shots during actual appearances; follows the actual team in each game.',
  'implementation_status': 'IMPLEMENTED',
  'SQL_view': 'player_offensive_advanced',
  'output_column': 'shot_share'}]

def write_dictionary(output):
    output=Path(output);output.mkdir(parents=True,exist_ok=True)
    with (output/'metric_dictionary.csv').open('w',newline='') as f:
        writer=csv.DictWriter(f,fieldnames=DEFINITIONS[0],lineterminator="\n");writer.writeheader();writer.writerows(DEFINITIONS)
